# -*- coding: utf-8 -*-
"""EDA_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t4t2B-GOZOoIBXydW7QFlmXD6Lrq6eyV
"""

pip install pypdf matplotlib wordcloud

import os
from pypdf import PdfReader
import matplotlib.pyplot as plt
from wordcloud import WordCloud

# 1. LOAD DATA
data_folder = '/content/Data'  # Point to your data folder
all_text = ""
page_counts = []

print(f"Loading PDFs from {data_folder}...")
for filename in os.listdir(data_folder):
    if filename.endswith('.pdf'):
        reader = PdfReader(os.path.join(data_folder, filename))
        num_pages = len(reader.pages)
        page_counts.append((filename, num_pages))

        # Extract text for WordCloud
        for page in reader.pages:
            all_text += page.extract_text() + " "

# 2. GENERATE GRAPH 1: Document Lengths
names = [x[0] for x in page_counts]
counts = [x[1] for x in page_counts]

plt.figure(figsize=(10, 5))
plt.bar(names, counts, color='skyblue')
plt.title('Document Complexity (Page Counts)')
plt.xlabel('Files')
plt.ylabel('Pages')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('eda_page_counts.png') # Save to show in report
plt.show()

# 3. GENERATE GRAPH 2: Knowledge Word Cloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(all_text)

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('Key Concepts in Knowledge Base')
plt.tight_layout()
plt.savefig('eda_wordcloud.png') # Save to show in report
plt.show()

print("EDA Completed. Images saved.")